### ISSUE TITLE
shrink error

### ISSUE THREAD

**Issue by godhj93** [j-marple-dev/model_compression#17]
Pruning 한 모델을  Shrink 하려 하는데 다음과 같은 에러가 납니다.
densenet_small_lth.py 를 가지고 Pruning하였고 `../../model_compression/my_work/models/LTH/171_62_87.pth.tar ` 이 경로에 Pruning된 weight이 저장되어있는데 제가 잘못하고있는건가요?

```
python shrink.py --config config/prune/cifar100/densenet_small_lth.py --checkpoint ../../model_compression/my_work/models/LTH/171_62_87.pth.tar 
2021-03-19 01:00:26,854 - config_validator.py:44 - INFO - [Config]	TRAIN_CONFIG: {'SEED': 777, 'AUG_TRAIN': 'randaugment_train_cifar100', 'AUG_TRAIN_PARAMS': {'n_select': 2, 'level': None}, 'AUG_TEST': 'simple_augment_test_cifar100', 'CUTMIX': {'beta': 1, 'prob': 0.5}, 'DATASET': 'CIFAR100', 'MODEL_NAME': 'densenet', 'MODEL_PARAMS': {'num_classes': 100, 'inplanes': 24, 'growthRate': 12, 'compressionRate': 2, 'block_configs': (16, 16, 16)}, 'CRITERION': 'CrossEntropy', 'CRITERION_PARAMS': {'num_classes': 100, 'label_smoothing': 0.1}, 'LR_SCHEDULER': 'WarmupCosineLR', 'LR_SCHEDULER_PARAMS': {'warmup_epochs': 10, 'start_lr': 0.001, 'min_lr': 1e-05, 'n_rewinding': 1}, 'BATCH_SIZE': 64, 'LR': 0.1, 'MOMENTUM': 0.9, 'WEIGHT_DECAY': 0.0001, 'EPOCHS': 300, 'N_WORKERS': 20}	N_PRUNING_ITER: 15	PRUNE_METHOD: LotteryTicketHypothesis	PRUNE_PARAMS: {'PRUNE_AMOUNT': 0.2, 'STORE_PARAM_BEFORE': 0, 'TRAIN_START_FROM': 0, 'PRUNE_AT_BEST': False}
2021-03-19 01:00:28,197 - trainer.py:71 - INFO - Created a model densenet with 0.78M params
2021-03-19 01:00:28,197 - trainer.py:74 - INFO - Setup train configuration
Files already downloaded and verified
2021-03-19 01:00:29,003 - trainer.py:98 - INFO - Datasets prepared
2021-03-19 01:00:29,003 - trainer.py:110 - INFO - Dataloader prepared
2021-03-19 01:00:29,319 - shrinker.py:92 - INFO - Initialize the model from the checkpoint ../../model_compression/my_work/models/LTH/171_62_87.pth.tar
Traceback (most recent call last):
  File "shrink.py", line 38, in <module>
    shrinker.run()
  File "/hdd_ext/hdd2000/add/add_temp/model_compression/src/runners/shrinker.py", line 100, in run
    _, acc = self.trainer.test_one_epoch()
  File "/hdd_ext/hdd2000/add/add_temp/model_compression/src/runners/trainer.py", line 251, in test_one_epoch
    return self.test_one_epoch_model(model)
  File "/home/hj/anaconda3/envs/ML/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/hdd_ext/hdd2000/add/add_temp/model_compression/src/runners/trainer.py", line 260, in test_one_epoch_model
    for data in progressbar(self.testloader, prefix="[Test]\t"):
TypeError: 'module' object is not callable

```

또한 Pruning한 모델을 가지고 테스트를 하고 싶은데 어떻게 모델을 불러오면 될까요?

**Comment by HSShin0** [comment]
Shink를 하려면 channel-wise pruning을 한 모델을 사용하셔야 합니다.
